// Curated list of Indian cities for the profile location picker:
// all 28 state capitals + 8 union-territory capitals + major metros and
// tier-1/tier-2 cities. Alphabetically sorted, de-duplicated. Users who don't
// find their city pick "Other" and type a free-form value (see location-select).

export const INDIA_CITIES = [
  'Agartala',
  'Agra',
  'Ahmedabad',
  'Aizawl',
  'Ajmer',
  'Amaravati',
  'Amritsar',
  'Aurangabad',
  'Belagavi',
  'Bengaluru',
  'Bhopal',
  'Bhubaneswar',
  'Chandigarh',
  'Chennai',
  'Coimbatore',
  'Daman',
  'Dehradun',
  'Dhanbad',
  'Dispur',
  'Faridabad',
  'Gandhinagar',
  'Gangtok',
  'Ghaziabad',
  'Gurugram',
  'Guwahati',
  'Gwalior',
  'Hubballi',
  'Hyderabad',
  'Imphal',
  'Indore',
  'Itanagar',
  'Jaipur',
  'Jammu',
  'Jamshedpur',
  'Jodhpur',
  'Kavaratti',
  'Kochi',
  'Kohima',
  'Kolkata',
  'Kollam',
  'Kota',
  'Kozhikode',
  'Leh',
  'Lucknow',
  'Madurai',
  'Mangaluru',
  'Meerut',
  'Mumbai',
  'Mysuru',
  'Nagpur',
  'Nashik',
  'New Delhi',
  'Noida',
  'Panaji',
  'Patna',
  'Port Blair',
  'Prayagraj',
  'Puducherry',
  'Pune',
  'Raipur',
  'Rajkot',
  'Ranchi',
  'Salem',
  'Shillong',
  'Shimla',
  'Solapur',
  'Srinagar',
  'Surat',
  'Thane',
  'Thiruvananthapuram',
  'Thrissur',
  'Tiruchirappalli',
  'Tirupati',
  'Udaipur',
  'Vadodara',
  'Varanasi',
  'Vijayawada',
  'Visakhapatnam',
  'Warangal',
] as const

export const OTHER_LOCATION_MAX = 100
