-- ============================================================
-- Stride Run Club — Complete Schema
-- Run this in Supabase Dashboard > SQL Editor
-- ============================================================

-- ──────────────────────────────────────────────────────────
-- UTILITY: updated_at trigger function
-- ──────────────────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ──────────────────────────────────────────────────────────
-- TABLE: users (member profiles)
-- ──────────────────────────────────────────────────────────
create table public.users (
  id             uuid references auth.users(id) on delete cascade primary key,
  username       text unique not null,
  full_name      text,
  bio            text,
  role           text not null default 'GUEST'
                   check (role in ('GUEST', 'MEMBER', 'ADMIN')),
  avatar_url     text,
  avatar_public  boolean not null default true,  -- DPDP: hide photo from public surfaces when false
  cover_url      text,
  location       text,
  skills         text,           -- JSON array of strings
  linkedin_url   text,
  instagram_url  text,
  strava_url     text,
  prompts        text,           -- JSON array of {question, answer}
  runs_completed int not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index users_username_idx on public.users (username);

alter table public.users enable row level security;

create policy "Profiles are publicly readable"
  on public.users for select
  using (true);

create policy "Users can update own profile"
  on public.users for update
  using (auth.uid() = id);

create trigger set_users_updated_at
  before update on public.users
  for each row execute procedure public.set_updated_at();

-- Auto-create profile on first sign-up
create or replace function public.handle_new_user()
returns trigger as $$
declare
  base_username  text;
  final_username text;
  suffix         int := 0;
begin
  base_username := lower(regexp_replace(
    coalesce(
      new.raw_user_meta_data ->> 'preferred_username',
      split_part(new.email, '@', 1)
    ),
    '[^a-z0-9]', '', 'g'
  ));

  -- Guarantee uniqueness by appending a numeric suffix if needed
  final_username := base_username;
  while exists (select 1 from public.users where username = final_username) loop
    suffix := suffix + 1;
    final_username := base_username || suffix::text;
  end loop;

  insert into public.users (id, username, full_name, avatar_url)
  values (
    new.id,
    final_username,
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'avatar_url'
  );

  return new;
end;
$$ language plpgsql security definer;

-- Drop first — Supabase pre-creates this trigger on all new projects
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ──────────────────────────────────────────────────────────
-- TABLE: events
-- ──────────────────────────────────────────────────────────
create table public.events (
  id               text primary key,         -- nanoid generated by server action
  name             text not null,
  slug             text unique not null,
  subtitle         text,
  description      text,
  details          text,                      -- long markdown body
  status           text not null default 'DRAFT'
                     check (status in ('DRAFT', 'PUBLISHED', 'CANCELLED')),
  event_date       timestamptz,
  end_date         timestamptz,
  location         text,
  location_url     text,                      -- Google Maps URL
  strava_route_url text,
  price_paise      int not null default 0,   -- 0 = free; ₹299 → 29900
  capacity         int,
  cover_url        text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index events_slug_idx       on public.events (slug);
create index events_status_idx     on public.events (status);
create index events_event_date_idx on public.events (event_date);

alter table public.events enable row level security;

create policy "Published events are publicly readable"
  on public.events for select
  using (status = 'PUBLISHED');

create policy "Admins can manage events"
  on public.events for all
  using (
    exists (
      select 1 from public.users
      where id = auth.uid() and role = 'ADMIN'
    )
  );

create trigger set_events_updated_at
  before update on public.events
  for each row execute procedure public.set_updated_at();

-- ──────────────────────────────────────────────────────────
-- TABLE: products
-- ──────────────────────────────────────────────────────────
create table public.products (
  id          text primary key,              -- nanoid generated by server action
  name        text not null,
  slug        text unique not null,
  description text,
  price_paise int not null,                  -- stored in paise (INR × 100)
  image_url   text,
  stock       int not null default 0,
  status      text not null default 'DRAFT'
                check (status in ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index products_slug_idx   on public.products (slug);
create index products_status_idx on public.products (status);

alter table public.products enable row level security;

create policy "Published products are publicly readable"
  on public.products for select
  using (status = 'PUBLISHED');

create policy "Admins can manage products"
  on public.products for all
  using (
    exists (
      select 1 from public.users
      where id = auth.uid() and role = 'ADMIN'
    )
  );

create trigger set_products_updated_at
  before update on public.products
  for each row execute procedure public.set_updated_at();

-- ──────────────────────────────────────────────────────────
-- TABLE: event_registrations
-- ──────────────────────────────────────────────────────────
create table public.event_registrations (
  id                  text primary key,      -- nanoid
  event_id            text not null references public.events(id) on delete cascade,
  user_id             uuid not null references public.users(id) on delete cascade,
  status              text not null default 'PENDING'
                        check (status in ('PENDING', 'CONFIRMED', 'CANCELLED')),
  cashfree_order_id   text,
  cashfree_payment_id text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (event_id, user_id)                -- prevent duplicate registrations
);

create index er_event_id_idx  on public.event_registrations (event_id);
create index er_user_id_idx   on public.event_registrations (user_id);
create index er_order_id_idx  on public.event_registrations (cashfree_order_id);

alter table public.event_registrations enable row level security;

create policy "Users can view own registrations"
  on public.event_registrations for select
  using (auth.uid() = user_id);

create policy "Users can insert own registrations"
  on public.event_registrations for insert
  with check (auth.uid() = user_id);

create policy "Admins can manage all registrations"
  on public.event_registrations for all
  using (
    exists (
      select 1 from public.users
      where id = auth.uid() and role = 'ADMIN'
    )
  );

create trigger set_er_updated_at
  before update on public.event_registrations
  for each row execute procedure public.set_updated_at();

-- ─── Transactional email idempotency stamps (Brevo) ──────────────────────────
-- Applied manually via the Supabase SQL Editor. The claim-then-send helpers in
-- src/lib/email/send-hooks.ts atomically stamp these columns so no email is
-- ever sent twice (paid registrations can be confirmed by both verify-payment
-- and the Razorpay webhook).
alter table public.users add column welcome_email_sent_at timestamptz;
alter table public.event_registrations add column confirmation_email_sent_at timestamptz;

-- Backfill: existing users must NOT receive a welcome email on their next sign-in
update public.users set welcome_email_sent_at = now();
-- Backfill: already-confirmed registrations must not get a late confirmation email
update public.event_registrations set confirmation_email_sent_at = now() where status = 'CONFIRMED';

-- ─── Atomic event-capacity guard (race-condition fix — CWE-362) ──────────────
-- Applied manually via the Supabase SQL Editor. MUST be run BEFORE deploying the
-- updated /api/events/register route, which calls this function via rpc().
--
-- The register route previously read the CONFIRMED count and then inserted in a
-- separate, non-atomic step, so two concurrent registrations for the last seat
-- could both pass the check and both insert — overbooking an event past its
-- capacity. This function closes that window: it takes a row lock on the event
-- (SELECT ... FOR UPDATE), so concurrent registrations for the SAME event
-- serialize on that lock; the CONFIRMED count is then re-read under the lock and
-- the row is inserted only if a seat is genuinely free — all in one transaction.
--
-- Semantics preserved from the previous application-level gate:
--   * capacity IS NULL  → unlimited (no cap enforced)
--   * only CONFIRMED rows count toward the cap (matches getConfirmedCount() and
--     the "spots left" display); PENDING holds are not counted
-- Returns one of:
--   'INSERTED'        → registration row created
--   'CAPACITY_FULL'   → event at capacity (route returns the existing 409 "Event is full")
--   'EVENT_NOT_FOUND' → no such event id
--
-- SECURITY DEFINER + execute restricted to service_role: the route's adminClient
-- (service_role) is the only caller. anon/authenticated must NOT be able to call
-- it directly, as it inserts a registration with a caller-supplied user_id/status
-- and would otherwise bypass RLS. Idempotent: safe to re-run.
create or replace function public.register_for_event(
  p_registration_id   text,
  p_event_id          text,
  p_user_id           text,
  p_status            text,
  p_custom_responses  text,
  p_razorpay_order_id text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_capacity  int;
  v_confirmed int;
begin
  -- Serialize concurrent registrations for this event; the lock is held until
  -- this function's transaction commits, so the count below sees every prior
  -- committed insert.
  select capacity into v_capacity
  from public.events
  where id = p_event_id
  for update;

  if not found then
    return 'EVENT_NOT_FOUND';
  end if;

  if v_capacity is not null then
    select count(*) into v_confirmed
    from public.event_registrations
    where event_id = p_event_id and status = 'CONFIRMED';

    if v_confirmed >= v_capacity then
      return 'CAPACITY_FULL';
    end if;
  end if;

  insert into public.event_registrations
    (id, event_id, user_id, status, razorpay_order_id, custom_responses)
  values
    (p_registration_id, p_event_id, p_user_id, p_status, p_razorpay_order_id, p_custom_responses);

  return 'INSERTED';
end;
$$;

revoke all    on function public.register_for_event(text, text, text, text, text, text) from public;
revoke all    on function public.register_for_event(text, text, text, text, text, text) from anon;
revoke all    on function public.register_for_event(text, text, text, text, text, text) from authenticated;
grant  execute on function public.register_for_event(text, text, text, text, text, text) to service_role;

-- ─── Profile shareability (DPDP) ──────────────────────────────────────────────
-- Applied manually via the Supabase SQL Editor. When false, the profile page is
-- owner/admin-only (404 for everyone else, direct URL included) and leaderboard
-- entries render unlinked. Replaces the former avatar_public photo toggle.
alter table public.users add column profile_public boolean not null default true;
-- Optional cleanup once deployed (no code reads it anymore):
-- alter table public.users drop column avatar_public;
